### ISSUE TITLE
Stemmer vises over to rader ved resize

### ISSUE THREAD

**Issue by stianfro** [jishono/jishono-adminclient#2]
Ved full bredde vises stemmer pent på 1 rad, men om man krymper siden litt går de fort over på 2 rader.

Føler noe kanskje kan tweakes for å holde det på 1 rad så langt der lar ser gjøre.

![image](https://user-images.githubusercontent.com/26657174/89312189-3f51d000-d677-11ea-96d5-4b873d18ffbc.png)

![image](https://user-images.githubusercontent.com/26657174/89312230-4e388280-d677-11ea-8e3a-4784ca394ecd.png)

**Comment by pergpau** [comment]
Fikset slik:
- Bruker flere columns for lg+
- Satt breakpoint for mobilvisning til 1024px (stor tablet)
- Tweaket ikonene så de tar litt mindre plass
